In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
import numpy as np
from sklearn_extensions.extreme_learning_machines.elm import ELMClassifier as elm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import mean_squared_error
import plotly.express as px

c:\users\asus\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass neg_label=-1, pos_label=1 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [2]:
data=pd.read_excel('ujian tesis.xlsx')
data

Jenis Kelamin Status Bekerja Status Berkeluarga      Usia  IP Semester 3  \
0       Perempuan             Ya                 Ya       Tua           3.43   
1       Laki-Laki             Ya                 Ya  Menengah           3.75   
2       Laki-Laki             Ya                 Ya  Menengah           3.58   
3       Laki-Laki             Ya                 Ya       Tua           3.40   
4       Laki-Laki             Ya                 Ya       Tua           4.00   
5       Perempuan             Ya                 Ya  Menengah           4.00   
6       Laki-Laki             Ya                 Ya       Tua           3.78   
7       Laki-Laki             Ya                 Ya  Menengah           4.00   
8       Laki-Laki             Ya                 Ya       Tua           3.33   
9       Laki-Laki             Ya                 Ya  Menengah           3.50   
10      Laki-Laki             Ya                 Ya  Menengah           4.00   
11      Perempuan             Ya                 Ya  Menengah           3.85   
12      Perempuan             Ya                 Ya  Menengah           3.58   
13      Perempuan             Ya                 Ya  Menengah           3.33   
14      Perempuan             Ya                 Ya  Menengah           3.58   
15      Laki-Laki             Ya                 Ya  Menengah           3.85   
16      Laki-Laki             Ya                 Ya  Menengah           3.43   
17      Laki-Laki             Ya                 Ya  Menengah           4.00   
18      Laki-Laki             Ya                 Ya       Tua           3.33   
19      Laki-Laki             Ya                 Ya  Menengah           3.38   
20      Perempuan             Ya                 Ya  Menengah           3.38   
21      Laki-Laki             Ya                 Ya       Tua           3.38   
22      Laki-Laki             Ya                 Ya  Menengah           3.38   
23      Laki-Laki             Ya                 Ya       Tua           3.38   
24      Laki-Laki             Ya                 Ya  Menengah           3.38   
25      Laki-Laki             Ya                 Ya  Menengah           3.38   
26      Laki-Laki             Ya                 Ya  Menengah           3.38   
27      Laki-Laki             Ya                 Ya  Menengah           3.38   
28      Laki-Laki             Ya                 Ya  Menengah           3.38   
29      Laki-Laki             Ya                 Ya  Menengah           3.75   
30      Laki-Laki             Ya                 Ya  Menengah           3.38   
31      Laki-Laki             Ya                 Ya  Menengah           3.38   
32      Laki-Laki             Ya                 Ya  Menengah           3.38   
33      Laki-Laki             Ya                 Ya  Menengah           3.38   
34      Perempuan             Ya                 Ya  Menengah           3.38   
35      Laki-Laki             Ya                 Ya  Menengah           3.38   
36      Laki-Laki             Ya                 Ya       Tua           3.38   
37      Laki-Laki             Ya                 Ya       Tua           3.38   
38      Laki-Laki             Ya                 Ya  Menengah           3.38   
39      Laki-Laki             Ya                 Ya  Menengah           3.38   
40      Perempuan             Ya                 Ya  Menengah           3.38   
41      Laki-Laki             Ya                 Ya       Tua           3.38   
42      Laki-Laki             Ya                 Ya  Menengah           3.38   
43      Laki-Laki             Ya                 Ya       Tua           3.38   
44      Laki-Laki             Ya                 Ya       Tua           3.38   
45      Perempuan             Ya                 Ya  Menengah           3.38   
46      Perempuan             Ya                 Ya  Menengah           3.38   
47      Laki-Laki             Ya                 Ya       Tua           3.38   
48      Laki-Laki             Ya                 Ya       Tua           3.38   
49  

In [3]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [4]:
le.fit(data['Usia'])
le.classes_

array(['Menengah', 'Muda', 'Tua'], dtype=object)

In [5]:
le = preprocessing.LabelEncoder()
data['Jenis Kelamin'] = le.fit_transform(data['Jenis Kelamin'].values)
data['Status Bekerja'] = le.fit_transform(data['Status Bekerja'].values)
data['Status Berkeluarga'] = le.fit_transform(data['Status Berkeluarga'].values)
data['Usia'] = le.fit_transform(data['Usia'].values)
data['Ujian Komprehensif'] = le.fit_transform(data['Ujian Komprehensif'].values)
data['Progres Disertasi'] = le.fit_transform(data['Progres Disertasi'].values)
data['Publikasi'] = le.fit_transform(data['Publikasi'].values)
data['Class'] = le.fit_transform(data['Class'].values)

In [6]:
print(data.info())
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Jenis Kelamin       110 non-null    int32  
 1   Status Bekerja      110 non-null    int32  
 2   Status Berkeluarga  110 non-null    int32  
 3   Usia                110 non-null    int32  
 4   IP Semester 3       110 non-null    float64
 5   Ujian Komprehensif  110 non-null    int32  
 6   Progres Disertasi   110 non-null    int32  
 7   Publikasi           110 non-null    int32  
 8   Class               110 non-null    int32  
dtypes: float64(1), int32(8)
memory usage: 4.4 KB
None


Jenis Kelamin  Status Bekerja  Status Berkeluarga  Usia  IP Semester 3  \
0              1               0                   1     2           3.43   
1              0               0                   1     0           3.75   
2              0               0                   1     0           3.58   
3              0               0                   1     2           3.40   
4              0               0                   1     2           4.00   

   Ujian Komprehensif  Progres Disertasi  Publikasi  Class  
0                   0                  2          2      0  
1                   1                  1          1      1  
2                   1                  2          2      0  
3                   1                  2          2      0  
4                   1                  2          2      0

In [7]:
X=data[['Jenis Kelamin','Status Bekerja','Status Berkeluarga','Usia','Ujian Komprehensif','Progres Disertasi','IP Semester 3','Publikasi']]
Y=data['Class']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 5)
print ("Data Training:", len(X_train))
print ("Data Testing:", len(X_test))

Data Training: 88
Data Testing: 22


In [18]:
X_train.values

array([[0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.88, 1.  ],
       [1.  , 0.  , 1.  , 0.  , 0.  , 2.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 3.88, 0.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.88, 1.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 2.  , 3.38, 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 2.  , 3.38, 2.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.58, 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [1.  , 0.  , 1.  , 0.  , 0.  , 2.  , 0.  , 2.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.33, 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 3.88, 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  , 2.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 0.  ,

In [19]:
X_test.values

array([[0.  , 0.  , 1.  , 0.  , 0.  , 2.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 4.  , 1.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 2.  , 3.38, 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [1.  , 0.  , 1.  , 2.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.25, 1.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 3.38, 0.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.63, 1.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 3.78, 1.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 3.38, 1.  ],
       [0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 4.  , 1.  ],
       [1.  , 0.  , 1.  , 0.  , 1.  , 2.  , 3.38, 2.  ],
       [1.  , 0.  , 1.  , 2.  ,

In [3]:
hidden_layer=[]
hasil=[]
for i in range(1,110):
    hiddenlayer=i*5
    elm_clf = elm(n_hidden=hiddenlayer, activation_func='sigmoid').fit(X_train.values, y_train)
    pred = elm_clf.predict(X_test)
    confusion_matrix(y_test, pred)
    hidden_layer.append(hiddenlayer)
    hasil.append(accuracy_score(pred, y_test))

NameError: name 'elm' is not defined

In [21]:
data=hidden_layer,hasil
hasil_akurasi=pd.DataFrame(data=data).transpose()
hasil_akurasi.columns=['hidden layer','akurasi']
hasil_akurasi

hidden layer   akurasi
0             5.0  0.909091
1            10.0  0.909091
2            15.0  0.909091
3            20.0  0.909091
4            25.0  0.909091
5            30.0  0.909091
6            35.0  0.818182
7            40.0  0.818182
8            45.0  0.863636
9            50.0  0.863636
10           55.0  0.818182
11           60.0  0.863636
12           65.0  0.818182
13           70.0  0.818182
14           75.0  0.863636
15           80.0  0.863636
16           85.0  0.818182
17           90.0  0.818182
18           95.0  0.863636
19          100.0  0.818182
20          105.0  0.863636
21          110.0  0.818182
22          115.0  0.863636
23          120.0  0.818182
24          125.0  0.863636
25          130.0  0.818182
26          135.0  0.818182
27          140.0  0.818182
28          145.0  0.818182
29          150.0  0.818182
30          155.0  0.818182
31          160.0  0.863636
32          165.0  0.818182
33          170.0  0.863636
34          175.0  0.863636
35          180.0  0.818182
36          185.0  0.818182
37          190.0  0.863636
38          195.0  0.818182
39          200.0  0.818182
40          205.0  0.818182
41          210.0  0.818182
42          215.0  0.863636
43          220.0  0.863636
44          225.0  0.818182
45          230.0  0.863636
46          235.0  0.818182
47          240.0  0.818182
48          245.0  0.863636
49          250.0  0.818182
50          255.0  0.818182
51          260.0  0.818182
52          265.0  0.863636
53          270.0  0.863636
54          275.0  0.818182
55          280.0  0.818182
56          285.0  0.863636
57          290.0  0.818182
58          295.0  0.863636
59          300.0  0.818182
60          305.0  0.818182
61          310.0  0.818182
62          315.0  0.818182
63          320.0  0.818182
64          325.0  0.863636
65          330.0  0.818182
66          335.0  0.818182
67          340.0  0.818182
68          345.0  0.818182
69          350.0  0.863636
70          355.0  0.818182
71          360.0  0.818182
72          365.0  0.818182
73          370.0  0.818182
74          375.0  0.863636
75          380.0  0.818182
76          385.0  0.863636
77          390.0  0.818182
78          395.0  0.818182
79          400.0  0.818182
80          405.0  0.818182
81          410.0  0.818182
82          415.0  0.863636
83          420.0  0.863636
84          425.0  0.818182
85          430.0  0.818182
86          435.0  0.863636
87          440.0  0.818182
88          445.0  0.818182
89          450.0  0.818182
90          455.0  0.863636
91          460.0  0.818182
92          465.0  0.863636
93          470.0  0.863636
94          475.0  0.818182
95          480.0  0.863636
96          485.0  0.818182
97          490.0  0.863636
98          495.0  0.863636
99          500.0  0.863636
100         505.0  0.863636
101         510.0  0.818182
102         515.0  0.818182
103         520.0  0.863636
104         525.0  0.818182
105         530.0  0.818182
106         535.0  0.863636
107         540.0  0.818182
108         545.0  0.863636

In [22]:
fig = px.line(hasil_akurasi, x="hidden layer", y="akurasi", title='Akurasi dan Hidden Layer')
fig.show()

In [23]:
from sklearn.metrics import mean_squared_error

from math import sqrt

rmse = sqrt(mean_squared_error(y_test, pred))

print(rmse)

0.3692744729379982


In [24]:
confusion_matrix(y_test, pred)

array([[ 6,  2],
       [ 1, 13]], dtype=int64)